---
- hosts:
  - localhost
  roles:
  - secrets
  - terraform
  - ovhdns
  - certbot
  gather_facts: no

- hosts: 
  - all
  roles:
  - wait
  gather_facts: no

- hosts:
    - proxy
    - server
  roles:
    - system
    - docker


- hosts:
    - proxy
  roles:
    - envoy

- hosts:
    - server
  roles:
    - microserver