---
- hosts:
  - localhost
  roles:
  - secrets
  - terraform
  gather_facts: no

- hosts: 
  - all
  roles:
  - wait
  gather_facts: no

- hosts:
    - proxy
    - server
  roles:
    - system
    - docker
#    - ovhdns

- hosts:
    - proxy
  roles:
    #- certbot
    - envoy

- hosts:
    - server
  roles:
    - microserver