---


- hosts:
  - localhost
  roles:
  - secrets
  - terraform
  - certbot
  gather_facts: False
  vars_files:
    - env.yml
  

- hosts: 
  - all
  roles:
  - wait
  gather_facts: False

- hosts:
    - all
  roles:
    - system
    - docker
  gather_facts: True
  vars_files:
    - env.yml

- hosts:
    - "{{cmk_group}}"
  roles:
    - checkmk
  gather_facts: True
  vars_files:
    - env.yml

- hosts:
    - "{{gra_group}}"
  roles:
    - grafana
    - loki
  gather_facts: True
  vars_files:
    - env.yml

- hosts:
    - "{{deployment}}-proxy-green"
    - "{{deployment}}-proxy-blue"
  roles:
    - envoy
  gather_facts: True
  vars_files:
    - env.yml

- hosts:
    - "{{deployment}}-backend-green"
    - "{{deployment}}-backend-blue"
  roles:
    - microserver
  gather_facts: True
  vars_files:
    - env.yml

- hosts: 
  - all
  roles:
  - wait
  gather_facts: True

- hosts: 
  - all
  roles:
  - checkmkagent
  - promtail
  gather_facts: True
  vars_files:
    - env.yml

- hosts:
    - "{{cmk_group}}"
  roles:
    - checkmkaddhosts
  gather_facts: True
  vars_files:
    - env.yml