- name: Create envoy config
  template:
    src: "{{ item }}"
    dest: "{{ item }}"
    mode: '0600'
  with_items:
    - docker-compose.yaml
    - Dockerfile-frontenvoy
    - front-envoy.yaml

- name: Start envoy
  shell: /home/ubuntu/.local/bin/docker-compose up --build -d
