- name: Set hostname
  become: yes
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add SSH-Keys
  shell: ssh-import-id gh:{{item}}
  with_items:
    - atrawog

# - name: Add Github Repo Keys
#   become: yes
#   shell: curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg

# - name: Add Github Repo
#   become: yes
#   shell: echo "deb [[arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null

- name: Upgrade packages
  become: yes
  apt:
    upgrade: safe
    update_cache: yes
    cache_valid_time: 3600

- name: Install tools + dependencies
  become: yes
  apt:
    name: 
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
        - dstat
        - htop
        - sysstat
        - iptraf
        - nethogs
        - python-is-python3
        - python3-docker
        - python3-pip
        - black
        - flake8
        - bzip2
        - nmon
        - conmon
        #- gh
        # - docker-compose
    state: present
    update_cache: no