- name: Set hostname
  become: yes
  hostname:
    name: "{{ inventory_hostname }}"

- name: Add SSH-Keys
  shell: ssh-import-id gh:{{item}}
  with_items:
    - atrawog

- name: Add letsencrypt-stg-root-x1
  become: yes 
  get_url:
    url: "https://letsencrypt.org/certs/staging/letsencrypt-stg-root-x1.pem"
    dest: "/etc/ssl/certs/letsencrypt-stg-root-x1.pem"
    mode: '0440'
  when: staging


- name: Upgrade packages
  become: yes
  apt:
    upgrade: safe
    update_cache: yes
    cache_valid_time: 3600

- name: Install tools + dependencies
  become: yes
  apt:
    name: 
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
        - dstat
        - htop
        - sysstat
        - iptraf
        - nethogs
        - python-is-python3
        - python3-docker
        - python3-pip
        - black
        - flake8
        - bzip2
        - nmon
        - conmon
        - unzip
        #- gh
        # - docker-compose
    state: present
    update_cache: no