- name: Create directory
  file:
    path: "{{certs}}"
    state: directory

- name: Create certs
  shell: "certbot certonly --test-cert --dns-ovh --non-interactive --agree-tos -m atrawog@gmail.com --dns-ovh-credentials .secrets/ovh.ini -d {{fqdn}} --work-dir {{certs}} --config-dir {{certs}} --logs-dir {{certs}}"
  ignore_errors: yes