static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/green/"
                route:
                  cluster: green
                  prefix_rewrite: "/"
              - match:
                  prefix: "/blue/"
                route:
                  cluster: blue
                  prefix_rewrite: "/"
              - match:
                  prefix: "/"
                route:
                  cluster: {{active}}

          http_filters:
          - name: envoy.filters.http.router

  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 8443
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: AUTO
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: backend
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/green/"
                route:
                  cluster: green
                  prefix_rewrite: "/"
              - match:
                  prefix: "/blue/"
                route:
                  cluster: blue
                  prefix_rewrite: "/"
              - match:
                  prefix: "/metrics"
                route:
                  cluster: admin
                  prefix_rewrite: "/stats/prometheus"
              - match:
                  prefix: "/"
                route:
                  cluster: {{active}}


          http_filters:
          - name: envoy.filters.http.router

      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
            - certificate_chain:
                filename: "/etc/fullchain.pem"
              private_key:
                filename: "/etc/privkey.pem"

  clusters:
  - name: green
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: green
      endpoints:
      - lb_endpoints:
{% for h in groups[deployment+'-backend-green'] %}
        - endpoint:
            address:
              socket_address:
                address: {{hostvars[h].ansible_host}}
                port_value: 80
{% endfor %}

  - name: blue
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: blue
      endpoints:
      - lb_endpoints:
{% for h in groups[deployment+'-backend-blue'] %}
        - endpoint:
            address:
              socket_address:
                address: {{hostvars[h].ansible_host}}
                port_value: 80
{% endfor %}

  - name: admin
    connect_timeout: 0.25s
    type: STATIC
    load_assignment: 
      cluster_name: admin
      endpoints:
        - lb_endpoints: 
          - endpoint:
              address: 
                socket_address:
                  address: 127.0.0.1
                  port_value: 9901
admin:
  address:
    socket_address:
      address: 0.0.0.0 
      port_value: 9901

layered_runtime:
  layers:
  - name: static_layer_0
    static_layer:
      envoy:
        resource_limits:
          listener:
            example_listener_name:
              connection_limit: 10000
