- name: Create terraform directory
  file:
    path: "{{tf_dir}}"
    state: directory


- name: Create Terraform config
  template:
    src: "{{item}}"
    dest: "{{tf_dir}}/{{item}}"
    mode: '0600'
  with_items:
    - terraform.tf
    - id_rsa.pub
    - provider.tf
    - ssh.tf
    - terraform.tf
    - instances.tf

- name: Deploy instances
  community.general.terraform:
    project_path: "{{tf_dir}}"
    state: present
    force_init: true
    workspace: "{{tf_workspace}}"

# - name: Init Terraform
#   shell: terraform -chdir={{tf_dir}} init

# - name: Apply Terraform
#   shell: terraform -chdir={{tf_dir}} init

- name: Refresh inventory
  meta: refresh_inventory

