server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://loki:{{gra_password}}@{{gra_fqdn}}/loki/api/v1/push
  

scrape_configs:
  - job_name: system 
    pipeline_stages:
      - docker: {}
    static_configs:
      - labels:
          job: docker
          host: {{ansible_hostname}}
          __path__: /var/lib/docker/containers/*/*-json.log
  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job: journal
        host: {{ansible_hostname}}
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'