name: "infrabuilder"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: "infrabuilder"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout builder
        uses: actions/checkout@v2
    
      - name: Checkout state
        uses: actions/checkout@v2
        with:
          repository: dorgeln/infrastate
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
          path: tf

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
          
      - name: Install Python dependencies
        run: pip install -r requirements.txt
        
      - name: Ansible Galaxy
        id: galaxy
        run: |
          ansible-galaxy collection install community.general
          ansible-galaxy collection install git+https://github.com/dorgeln/infra-ovh-ansible-module
          ansible-galaxy install maresb.micromamba
          ansible-galaxy install geerlingguy.docker 

      - name: Deploy system
        id: deploy
        run: ansible-playbook -vvv site.yml
        env:
          DEPLOYMENT: ${{secrets.DEPLOYMENT}}
          WORKSPACE: ${{secrets.WORKSPACE}}
          ACTIVE: ${{secrets.ACTIVE}}
          DOMAIN: ${{secrets.DOMAIN}}
          PROVIDER: ${{secrets.PROVIDER}}
          USER: ${{secrets.USER}}
          EMAIL: ${{secrets.EMAIL}}
          STAGING: ${{secrets.STAGING}}
          GMM_HOSTNAME: ${{secrets.GMM_HOSTNAME}}
          GMM_HOSTNAME_GREEN: ${{secrets.GMM_HOSTNAME_GREEN}}
          GMM_HOSTNAME_BLUE: ${{secrets.GMM_HOSTNAME_BLUE}}
          GMM_PROXY_GREEN_REGIONS: ${{secrets.GMM_PROXY_GREEN_REGIONS}}
          GMM_PROXY_GREEN_IMAGE: ${{secrets.GMM_PROXY_GREEN_IMAGE}}
          GMM_PROXY_GREEN_FLAVOR: ${{secrets.GMM_PROXY_GREEN_FLAVOR}}
          GMM_BACKEND_GREEN_REGIONS: ${{secrets.GMM_BACKEND_GREEN_REGIONS}}
          GMM_BACKEND_GREEN_IMAGE: ${{secrets.GMM_BACKEND_GREEN_IMAGE}}
          GMM_BACKEND_GREEN_FLAVOR: ${{secrets.GMM_BACKEND_GREEN_FLAVOR}}
          GMM_PROXY_BLUE_REGIONS: ${{secrets.GMM_PROXY_BLUE_REGIONS}}
          GMM_PROXY_BLUE_IMAGE: ${{secrets.GMM_PROXY_BLUE_IMAGE}}
          GMM_PROXY_BLUE_FLAVOR: ${{secrets.GMM_PROXY_BLUE_FLAVOR}}
          GMM_BACKEND_BLUE_REGIONS: ${{secrets.GMM_BACKEND_BLUE_REGIONS}}
          GMM_BACKEND_BLUE_IMAGE: ${{secrets.GMM_BACKEND_BLUE_IMAGE}}
          GMM_BACKEND_BLUE_FLAVOR: ${{secrets.GMM_BACKEND_BLUE_FLAVOR}}
          CMK_HOSTNAME: ${{secrets.CMK_HOSTNAME}}
          CMK_HOSTNAME_GREEN: ${{secrets.CMK_HOSTNAME_GREEN}}
          CMK_HOSTNAME_BLUE: ${{secrets.CMK_HOSTNAME_BLUE}}
          CMK_PASSWORD: ${{secrets.CMK_PASSWORD}}
          CMK_SECRET: ${{secrets.CMK_SECRET}}
          CMK_GREEN_REGIONS: ${{secrets.CMK_GREEN_REGIONS}}
          CMK_GREEN_IMAGE: ${{secrets.CMK_GREEN_IMAGE}}
          CMK_GREEN_FLAVOR: ${{secrets.CMK_GREEN_FLAVOR}}
          CMK_BLUE_REGIONS: ${{secrets.CMK_BLUE_REGIONS}}
          CMK_BLUE_IMAGE: ${{secrets.CMK_BLUE_IMAGE}}
          CMK_BLUE_FLAVOR: ${{secrets.CMK_BLUE_FLAVOR}}
          TF_VAR_endpoint: ${{secrets.TF_VAR_endpoint}}
          TF_VAR_application_key: ${{secrets.TF_VAR_application_key}}
          TF_VAR_application_secret: ${{secrets.TF_VAR_application_secret}}
          TF_VAR_consumer_key: ${{secrets.TF_VAR_consumer_key}}
          TF_VAR_project: ${{secrets.TF_VAR_project}}
          TF_VAR_instance: ${{secrets.TF_VAR_instance}}
          TF_VAR_auth_url: ${{secrets.TF_VAR_auth_url}}
          TF_VAR_user_name: ${{secrets.TF_VAR_user_name}}
          TF_VAR_password: ${{secrets.TF_VAR_password}}
          TF_VAR_user_domain_name: ${{secrets.TF_VAR_user_domain_name}}
          TF_VAR_tenant_name: ${{secrets.TF_VAR_tenant_name}}
          TF_VAR_tenant_id: ${{secrets.TF_VAR_tenant_id}}
          SSH_KEY_PUB: ${{secrets.SSH_KEY_PUB}}
          SSH_KEY_PRIV: ${{secrets.SSH_KEY_PRIV}}
        continue-on-error: true

      - name: Commit Terraform State
        run: |
          git config --global user.name 'infrabuilder'
          git config --global user.email 'infrabuilder@users.noreply.github.com'
          pushd tf
          git add -A
          git diff-index --quiet HEAD || git commit -am `date "+%F-%H-%M-%S"`
          git push

      - name: Ansible Deploy Status
        if: steps.deploy.outcome == 'failure'
        run: exit 1