name: "infrabuilder"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: "infrabuilder"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout builder
        uses: actions/checkout@v2
    
      - name: Checkout state
        uses: actions/checkout@v2
        with:
          repository: dorgeln/infrastate
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
          path: tf

      - name: Create env
        id: env
        run: ./micromamba create --file environment.yml --yes -r $PWD/.micromamba

      - name: Set PATH
        shell: bash
        run: |
          echo "${HOME}/.micromamba" >> $GITHUB_PATH
          echo GITHUB_PATH: $GITHUB_PATH

      - name: Ansible Galaxy
        id: galaxy
        run: |
          ansible-galaxy collection install community.general
          # ansible-galaxy collection install git+https://github.com/dorgeln/infra-ovh-ansible-module
          # ansible-galaxy install maresb.micromamba
          # ansible-galaxy install geerlingguy.docker 

      - name: Deploy system
        id: deploy
        run: ansible-playbook site.yml
        env:
          DEPLOYMENT: ${{secrets.DEPLOYMENT}}
          WORKSPACE: ${{secrets.WORKSPACE}}
          STAGING: ${{secrets.STAGING}}
          ALIAS: ${{secrets.ALIAS}}     
          ALIAS2: ${{secrets.ALIAS2}}   
          DOMAIN: ${{secrets.DOMAIN}}
          DOMAIN2: ${{secrets.DOMAIN}}
          ACTIVE: ${{secrets.ACTIVE}}
          PROVIDER: ${{secrets.PROVIDER}}
          USER: ${{secrets.USER}}
          EMAIL: ${{secrets.EMAIL}}

          GRA_ID: ${{secrets.GRA_ID}}
          GRA_REGION: ${{secrets.GRA_REGION}}
          GRA_IMAGE: ${{secrets.GRA_IMAGE}}
          GRA_FLAVOR: ${{secrets.GRA_FLAVOR}}
          GRA_PASSWORD: ${{secrets.GRA_PASSWORD}}

          CMK_ID: ${{secrets.CMK_ID}}
          CMK_REGION: ${{secrets.CMK_REGION}}
          CMK_IMAGE: ${{secrets.CMK_IMAGE}}
          CMK_FLAVOR: ${{secrets.CMK_FLAVOR}}
          CMK_PASSWORD: ${{secrets.CMK_PASSWORD}}
          CMK_SECRET: ${{secrets.CMK_SECRET}}

          GMM_ID: ${{secrets.GMM_ID}}
          GMM_PROXY_GREEN_REGIONS: ${{secrets.GMM_PROXY_GREEN_REGIONS}}
          GMM_PROXY_GREEN_IMAGE: ${{secrets.GMM_PROXY_GREEN_IMAGE}}
          GMM_PROXY_GREEN_FLAVOR: ${{secrets.GMM_PROXY_GREEN_FLAVOR}}
          GMM_BACKEND_GREEN_REGIONS: ${{secrets.GMM_BACKEND_GREEN_REGIONS}}
          GMM_BACKEND_GREEN_IMAGE: ${{secrets.GMM_BACKEND_GREEN_IMAGE}}
          GMM_BACKEND_GREEN_FLAVOR: ${{secrets.GMM_BACKEND_GREEN_FLAVOR}}
          GMM_PROXY_BLUE_REGIONS: ${{secrets.GMM_PROXY_BLUE_REGIONS}}
          GMM_PROXY_BLUE_IMAGE: ${{secrets.GMM_PROXY_BLUE_IMAGE}}
          GMM_PROXY_BLUE_FLAVOR: ${{secrets.GMM_PROXY_BLUE_FLAVOR}}
          GMM_BACKEND_BLUE_REGIONS: ${{secrets.GMM_BACKEND_BLUE_REGIONS}}
          GMM_BACKEND_BLUE_IMAGE: ${{secrets.GMM_BACKEND_BLUE_IMAGE}}
          GMM_BACKEND_BLUE_FLAVOR: ${{secrets.GMM_BACKEND_BLUE_FLAVOR}}

          TF_VAR_endpoint: ${{secrets.TF_VAR_endpoint}}
          TF_VAR_application_key: ${{secrets.TF_VAR_application_key}}
          TF_VAR_application_secret: ${{secrets.TF_VAR_application_secret}}
          TF_VAR_consumer_key: ${{secrets.TF_VAR_consumer_key}}
          TF_VAR_project: ${{secrets.TF_VAR_project}}
          TF_VAR_instance: ${{secrets.TF_VAR_instance}}
          TF_VAR_auth_url: ${{secrets.TF_VAR_auth_url}}
          TF_VAR_user_name: ${{secrets.TF_VAR_user_name}}
          TF_VAR_password: ${{secrets.TF_VAR_password}}
          TF_VAR_user_domain_name: ${{secrets.TF_VAR_user_domain_name}}
          TF_VAR_tenant_name: ${{secrets.TF_VAR_tenant_name}}
          TF_VAR_tenant_id: ${{secrets.TF_VAR_tenant_id}}
          SSH_KEY_PUB: ${{secrets.SSH_KEY_PUB}}
          SSH_KEY_PRIV: ${{secrets.SSH_KEY_PRIV}}
        continue-on-error: true

      - name: Commit Terraform State
        run: |
          git config --global user.name 'infrabuilder'
          git config --global user.email 'infrabuilder@users.noreply.github.com'
          pushd tf
          git add -A
          git diff-index --quiet HEAD || git commit -am `date "+%F-%H-%M-%S"`
          git push

      - name: Ansible Deploy Status
        if: steps.deploy.outcome == 'failure'
        run: exit 1