name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout builder
        uses: actions/checkout@v2
    
      - name: Checkout state
        uses: actions/checkout@v2
        with:
          repository: dorgeln/infrastate
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
          path: terraform

      - name: Create test file
        run: date +%s > terraform/test.txt
      - name: Commit test
        run: |
          git config --global user.name 'Infrabuilder'
          git config --global user.email 'infrabuilder@users.noreply.github.com'
          pushd terraform
          git add -A
          git commit -am "Automated test"
          git push
 