name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout builder
        uses: actions/checkout@v2
    
      - name: Checkout state
        uses: actions/checkout@v2
        with:
          repository: dorgeln/infrastate
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
          path: tf

      - name: create Terrafrom config
        uses: dorgeln/action-ansible-playbook@v2
        with:
          playbook: tf_config.yml
          directory: ./
          options: |
            -e SSH_KEY_PUB='${{ secrets.SSH_KEY_PUB }}'
            -e SSH_KEY_PRIV='${{ secrets.SSH_KEY_PRIV }}'
            --verbose

      - name: Commit state
        run: |
          git config --global user.name 'infrabuilder'
          git config --global user.email 'infrabuilder@users.noreply.github.com'
          pushd tf
          git add -A
          git commit -am `date "+%F-%H-%M-%S"`
          git push
 